apiVersion: v1
kind: Secret
metadata:
 name: settings-xml
type: service.binding/maven
stringData:
 type: maven
 provider: sample
 settings.xml: |
   <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
       <mirrors>
           <mirror>
               <id>reposilite</id>
               <name>Tanzu seal Internal Repo</name>
               <url>https://reposilite.reposiliteurl.tap.tanzupartnerdemo.com/releases</url>
               <mirrorOf>*</mirrorOf>
           </mirror>
       </mirrors>
       <servers>
            <server>
               <id>reposilite</id>
               <username>admin</username>
               <password>Welcome11!</password>
            </server>
       </servers>
   </settings>
