profile: full
shared:
  ingress_domain: SESSION_NAME.demo.tanzupartnerdemo.com
  image_registry:
    project_path: "harborairgap.tanzupartnerdemo.com/SESSION_NAME/tap-packages"
    username: "admin"
    password: "Harbor12345"
  ca_cert_data:  |
            -----BEGIN CERTIFICATE-----
            MIIF2DCCBMCgAwIBAgIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDQYJKoZIhvcNAQEL
            BQAwgbUxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcM
            CUJlbmdhbHVydTEOMAwGA1UECgwFVGFuenUxGTAXBgNVBAsMEFRhbnp1cGFydG5l
            cmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNv
            bTEnMCUGCSqGSIb3DQEJARYYZWtuYXRoLnJlZGR5MDlAZ21haWwuY29tMB4XDTIy
            MTEyNTA2NDMwMFoXDTMyMTEyMjA2NDMwMFowgbUxCzAJBgNVBAYTAklOMRIwEAYD
            VQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcMCUJlbmdhbHVydTEOMAwGA1UECgwFVGFu
            enUxGTAXBgNVBAsMEFRhbnp1cGFydG5lcmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFp
            cmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTEnMCUGCSqGSIb3DQEJARYYZWtuYXRo
            LnJlZGR5MDlAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
            AQEAp1DRXGwK/XOzsweTFABjY0Jg9T9h/XJ/zRuCmxPKIx+J43TP2zEJDTbnO1kE
            qP1xzaLMXciy+5MdF4w2v8Gu4tYCDpA5gX4hnQflqiErUjRjIc1K0NykphjhB9Ae
            0f0jSQCCrHAVSVNeGhfAyWiJVgUkV0wyo4VnZRcx7MjsKc/zqL0BCaVv+w5ZQbF8
            OIEnWa3RUjJrnK2Y6rMld1EPKOzJiF3XnKHhvfk7JXw4eKbHCfuKghP213WAvWNz
            nnuDn9Sjj3xqvWvwG/QOf5T638pWouAhd4TDOE32ZOvYSSexTDgsxCfonL++6DVO
            9ibu+U6hZhpKx2VwxuADTGweJwIDAQABo4IB3DCCAdgwHQYDVR0OBBYEFD2azN5b
            S0xWLOwbJ+Z3C/jcLEWEMIH1BgNVHSMEge0wgeqAFD2azN5bS0xWLOwbJ+Z3C/jc
            LEWEoYG7pIG4MIG1MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS0FSTkFUQUtBMRIw
            EAYDVQQHDAlCZW5nYWx1cnUxDjAMBgNVBAoMBVRhbnp1MRkwFwYDVQQLDBBUYW56
            dXBhcnRuZXJkZW1vMSowKAYDVQQDDCFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVy
            ZGVtby5jb20xJzAlBgkqhkiG9w0BCQEWGGVrbmF0aC5yZWRkeTA5QGdtYWlsLmNv
            bYIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
            AvwwUQYDVR0RBEowSIIhaGFyYm9yYWlyZ2FwLnRhbnp1cGFydG5lcmRlbW8uY29t
            giMqLmhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTBRBgNVHRIESjBI
            giFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVyZGVtby5jb22CIyouaGFyYm9yYWly
            Z2FwLnRhbnp1cGFydG5lcmRlbW8uY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBCDnsJ
            l2n2UkQ6nWxevgsle7Kl0lJLbQn0y5/4i31LQIlr0wb9pKHZ8nX0I1BkkrIfqwTl
            QdAp+ItfJ+3tQYwxFtPUa8dog4ExBa+wk9tOU8U//wrkrUo3jv3I0ej2caXBFI3f
            I0vsyHF9z4FjtwmwXEMTIultbaIoN3ZZQRzqTn/y/AbgtHL7DtjeGR8TXQVsGHpJ
            tMAfLoyCFm9RDO80AZ2rjc+bO3PFULfYZEC4g895tcCHsVWnvCO1+WXXzZkdxw8o
            u2BgUILpgSsDI2y3wCK2ieUvRnY+wkBU+0nDqA/vlZWlKlGg0ghFQteLSSSz+RDH
            JDv41L6QuETb0Gv0
            -----END CERTIFICATE-----
    #            -----BEGIN CERTIFICATE-----MIIF2DCCBMCgAwIBAgIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDQYJKoZIhvcNAQELBQAwgbUxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcMCUJlbmdhbHVydTEOMAwGA1UECgwFVGFuenUxGTAXBgNVBAsMEFRhbnp1cGFydG5lcmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTEnMCUGCSqGSIb3DQEJARYYZWtuYXRoLnJlZGR5MDlAZ21haWwuY29tMB4XDTIyMTEyNTA2NDMwMFoXDTMyMTEyMjA2NDMwMFowgbUxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcMCUJlbmdhbHVydTEOMAwGA1UECgwFVGFuenUxGTAXBgNVBAsMEFRhbnp1cGFydG5lcmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTEnMCUGCSqGSIb3DQEJARYYZWtuYXRoLnJlZGR5MDlAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp1DRXGwK/XOzsweTFABjY0Jg9T9h/XJ/zRuCmxPKIx+J43TP2zEJDTbnO1kEqP1xzaLMXciy+5MdF4w2v8Gu4tYCDpA5gX4hnQflqiErUjRjIc1K0NykphjhB9Ae0f0jSQCCrHAVSVNeGhfAyWiJVgUkV0wyo4VnZRcx7MjsKc/zqL0BCaVv+w5ZQbF8OIEnWa3RUjJrnK2Y6rMld1EPKOzJiF3XnKHhvfk7JXw4eKbHCfuKghP213WAvWNznnuDn9Sjj3xqvWvwG/QOf5T638pWouAhd4TDOE32ZOvYSSexTDgsxCfonL++6DVO9ibu+U6hZhpKx2VwxuADTGweJwIDAQABo4IB3DCCAdgwHQYDVR0OBBYEFD2azN5bS0xWLOwbJ+Z3C/jcLEWEMIH1BgNVHSMEge0wgeqAFD2azN5bS0xWLOwbJ+Z3C/jcLEWEoYG7pIG4MIG1MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS0FSTkFUQUtBMRIwEAYDVQQHDAlCZW5nYWx1cnUxDjAMBgNVBAoMBVRhbnp1MRkwFwYDVQQLDBBUYW56dXBhcnRuZXJkZW1vMSowKAYDVQQDDCFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVyZGVtby5jb20xJzAlBgkqhkiG9w0BCQEWGGVrbmF0aC5yZWRkeTA5QGdtYWlsLmNvbYIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAvwwUQYDVR0RBEowSIIhaGFyYm9yYWlyZ2FwLnRhbnp1cGFydG5lcmRlbW8uY29tgiMqLmhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTBRBgNVHRIESjBIgiFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVyZGVtby5jb22CIyouaGFyYm9yYWlyZ2FwLnRhbnp1cGFydG5lcmRlbW8uY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBCDnsJl2n2UkQ6nWxevgsle7Kl0lJLbQn0y5/4i31LQIlr0wb9pKHZ8nX0I1BkkrIfqwTlQdAp+ItfJ+3tQYwxFtPUa8dog4ExBa+wk9tOU8U//wrkrUo3jv3I0ej2caXBFI3fI0vsyHF9z4FjtwmwXEMTIultbaIoN3ZZQRzqTn/y/AbgtHL7DtjeGR8TXQVsGHpJtMAfLoyCFm9RDO80AZ2rjc+bO3PFULfYZEC4g895tcCHsVWnvCO1+WXXzZkdxw8ou2BgUILpgSsDI2y3wCK2ieUvRnY+wkBU+0nDqA/vlZWlKlGg0ghFQteLSSSz+RDHJDv41L6QuETb0Gv0-----END CERTIFICATE-----
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  exclude_dependencies: true
  kp_default_repository: "harborairgap.tanzupartnerdemo.com/SESSION_NAME/build-service"
  kp_default_repository_username: "admin"
  kp_default_repository_password: "Harbor12345"
  ca_cert_data:  |
            -----BEGIN CERTIFICATE-----
            MIIF2DCCBMCgAwIBAgIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDQYJKoZIhvcNAQEL
            BQAwgbUxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcM
            CUJlbmdhbHVydTEOMAwGA1UECgwFVGFuenUxGTAXBgNVBAsMEFRhbnp1cGFydG5l
            cmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNv
            bTEnMCUGCSqGSIb3DQEJARYYZWtuYXRoLnJlZGR5MDlAZ21haWwuY29tMB4XDTIy
            MTEyNTA2NDMwMFoXDTMyMTEyMjA2NDMwMFowgbUxCzAJBgNVBAYTAklOMRIwEAYD
            VQQIDAlLQVJOQVRBS0ExEjAQBgNVBAcMCUJlbmdhbHVydTEOMAwGA1UECgwFVGFu
            enUxGTAXBgNVBAsMEFRhbnp1cGFydG5lcmRlbW8xKjAoBgNVBAMMIWhhcmJvcmFp
            cmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTEnMCUGCSqGSIb3DQEJARYYZWtuYXRo
            LnJlZGR5MDlAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
            AQEAp1DRXGwK/XOzsweTFABjY0Jg9T9h/XJ/zRuCmxPKIx+J43TP2zEJDTbnO1kE
            qP1xzaLMXciy+5MdF4w2v8Gu4tYCDpA5gX4hnQflqiErUjRjIc1K0NykphjhB9Ae
            0f0jSQCCrHAVSVNeGhfAyWiJVgUkV0wyo4VnZRcx7MjsKc/zqL0BCaVv+w5ZQbF8
            OIEnWa3RUjJrnK2Y6rMld1EPKOzJiF3XnKHhvfk7JXw4eKbHCfuKghP213WAvWNz
            nnuDn9Sjj3xqvWvwG/QOf5T638pWouAhd4TDOE32ZOvYSSexTDgsxCfonL++6DVO
            9ibu+U6hZhpKx2VwxuADTGweJwIDAQABo4IB3DCCAdgwHQYDVR0OBBYEFD2azN5b
            S0xWLOwbJ+Z3C/jcLEWEMIH1BgNVHSMEge0wgeqAFD2azN5bS0xWLOwbJ+Z3C/jc
            LEWEoYG7pIG4MIG1MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS0FSTkFUQUtBMRIw
            EAYDVQQHDAlCZW5nYWx1cnUxDjAMBgNVBAoMBVRhbnp1MRkwFwYDVQQLDBBUYW56
            dXBhcnRuZXJkZW1vMSowKAYDVQQDDCFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVy
            ZGVtby5jb20xJzAlBgkqhkiG9w0BCQEWGGVrbmF0aC5yZWRkeTA5QGdtYWlsLmNv
            bYIUE4AKLlArqASzLq3RNL1HOdJHyJ4wDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
            AvwwUQYDVR0RBEowSIIhaGFyYm9yYWlyZ2FwLnRhbnp1cGFydG5lcmRlbW8uY29t
            giMqLmhhcmJvcmFpcmdhcC50YW56dXBhcnRuZXJkZW1vLmNvbTBRBgNVHRIESjBI
            giFoYXJib3JhaXJnYXAudGFuenVwYXJ0bmVyZGVtby5jb22CIyouaGFyYm9yYWly
            Z2FwLnRhbnp1cGFydG5lcmRlbW8uY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBCDnsJ
            l2n2UkQ6nWxevgsle7Kl0lJLbQn0y5/4i31LQIlr0wb9pKHZ8nX0I1BkkrIfqwTl
            QdAp+ItfJ+3tQYwxFtPUa8dog4ExBa+wk9tOU8U//wrkrUo3jv3I0ej2caXBFI3f
            I0vsyHF9z4FjtwmwXEMTIultbaIoN3ZZQRzqTn/y/AbgtHL7DtjeGR8TXQVsGHpJ
            tMAfLoyCFm9RDO80AZ2rjc+bO3PFULfYZEC4g895tcCHsVWnvCO1+WXXzZkdxw8o
            u2BgUILpgSsDI2y3wCK2ieUvRnY+wkBU+0nDqA/vlZWlKlGg0ghFQteLSSSz+RDH
            JDv41L6QuETb0Gv0
            -----END CERTIFICATE-----
supply_chain: basic
ootb_supply_chain_basic:
  registry:
    server: "harborairgap.tanzupartnerdemo.com"
    repository: "SESSION_NAME/build-service"
  gitops:
      ssh_secret: "git-secret"
excluded_packages:
- policy.apps.tanzu.vmware.com
appliveview:
  ingressEnabled: true
  ingressDomain: "tanzupartnerdemo.com"
appliveview_connector:
  backend:
    sslDisabled: "true"
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "SESSION_NAME.demo.tanzupartnerdemo.com"
  app_config:
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
              name: host
              authProvider: serviceAccount
              serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
              skipTLSVerify: false
              caData: providecadata
    app:
      baseUrl: http://tap-gui.SESSION_NAME.demo.tanzupartnerdemo.com
    catalog:
      locations:
        - type: url
          target: https://giteaairgap.tap.tanzupartnerdemo.com/admin-airgap/tanzu-java-web-app/src/branch/main/catalog/catalog-info.yaml
        - type: url
          target: https://giteaairgap.tap.tanzupartnerdemo.com/admin-airgap/partnertapdemo-app/src/branch/main/catalog/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.SESSION_NAME.demo.tanzupartnerdemo.com
      cors:
        origin: http://tap-gui.SESSION_NAME.demo.tanzupartnerdemo.com
    integrations:
      github:
      - host: github.com
        token: ghp_bb84c47d78a0d7c72e8e62128e510eff0af4acd8
#metadata_store:
#  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP
scanning:
  metadataStore:
    url: "" # Disable embedded integration since it's deprecated
grype:
  namespace: "tap-install" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"
contour:
  infrastructure_provider: aws
  envoy:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
